### PR TITLE
Signed GPG Agreement

### PR DESCRIPTION
**Pull request by jcassou**

### CODE REVIEW

**Comment by jcassou** [comment]
The GPG key is now verified

**Comment by sangkilc** [comment]
Do not change Agreement.md. You should create your own file. Since there is a conflict, you'd better kill all the commits you made, and create a single commit that contains your new MD file.

**Comment by jcassou** [comment]
How is it possible to kill all the commits. I tried git reverse <commit_ID> but it doesn't work.

**Comment by sangkilc** [comment]
Since the modification is very small, it would be easier for you to delete your current repo and start from the beginning.

**Pull request closed without merging**
